#!/usr/bin/env node

var
  program = require('commander'),
  util = require('util'),
  exec = require('child_process').exec,
  fs = require('fs'),
  start_home = process.env['HOME'] + '/.start',
  appStarted = false,
  apps,
  init, parseFiles, parseApp, startApp, debug;

debug = function (message) {
  if (program.debug) {
    console.log(message);
  }
};

init = function () {
  fs.readdir(start_home + '/apps', function (err, files) {
    if (err) {
      console.error('Could not read apps dir');
      return;
    }
    parseFiles(files);
  });
};

parseFiles = function (files) {

  debug('parsing files');

  files.forEach(function( file ) {
    debug('parsing ' + file);
    parseApp(JSON.parse(fs.readFileSync(start_home + '/apps/' + file)));
  });
};

parseApp = function (appJson) {
  var realPath;

  appJson.directories.forEach(function( dir ) {
    realPath = fs.realpathSync( dir );

    debug("real path   : " + realPath);
    debug("current dir : " + process.cwd());

    if (realPath === process.cwd()) {
      debug("starting app");
      startApp(appJson.start_command);
    }
  });
};

startApp = function (cmd) {
  var proc;
  debug("running : " + cmd);
  proc = exec(cmd);
  proc.stdout.setEncoding('utf8');
  proc.stdout.on('data', util.print);
  proc.stderr.on('data', util.print);
};

program
  .version('0.0.0')
  .option('-d, --debug', 'logs debug statements')
  .parse(process.argv);



init();
