#!/usr/bin/env node
var util = require('util'),
  spawn = require('child_process').spawn,
  fs = require('fs'),
  start_home = process.env['HOME'] + '/.start',
  appStarted = false,
  apps,
  init, parseFiles, parseApp, startApp;

init = function () {
  fs.readdir(start_home + '/apps', function (err, files) {
    if (err) {
      console.error('Could not read apps dir');
      return;
    }
    parseFiles(files);
  });
};

parseFiles = function (files) {
  files.forEach(function( file ) {
    parseApp(JSON.parse(fs.readFileSync(start_home + '/apps/' + file)));
  });
};

parseApp = function (appJson) {
  var realPath;

  appJson.directories.forEach(function( dir ) {
    realPath = fs.realpathSync( dir );
    if (realPath === process.cwd()) {
      startApp(appJson.start_command);
    }
  });
};

startApp = function (cmd) {
  var proc;

  proc = spawn(cmd);
  proc.stdout.setEncoding('utf8');
  proc.stdout.on('data', util.print);
};

init();
